# Railway configuration for full-stack app
[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm run start:production"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  NODE_ENV = "production" 