[build]
  builder = "nixpacks"

[deploy]
  numReplicas = 1
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[[services]]
  name = "yahtzee-backend"
  source = "server"
  
  [services.build]
    buildCommand = "npm install"
    
  [services.deploy]
    startCommand = "npm start"
    healthcheckPath = "/health"
    healthcheckTimeout = 10
    
  [[services.variables]]
    name = "NODE_ENV"
    value = "production"
    
  [[services.variables]]
    name = "PORT"
    value = "${{ PORT }}"

[[services]]
  name = "yahtzee-frontend"
  source = "."
  
  [services.build]
    buildCommand = "npm install && npm run build"
    
  [services.deploy]
    startCommand = "npm run preview"
    
  [[services.variables]]
    name = "NODE_ENV" 
    value = "production"
    
  [[services.variables]]
    name = "VITE_API_URL"
    value = "${{ yahtzee-backend.RAILWAY_PUBLIC_DOMAIN }}" 